HammadBroker.Web/Areas/Admin/Controllers/CitiesController.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net;
using System.Threading;
using System.Threading.Tasks;
using AutoMapper;
using essentialMix.Core.Web.Controllers;
using essentialMix.Patterns.Pagination;
using essentialMix.Patterns.Sorting;
using HammadBroker.Data.Services;
using HammadBroker.Model;
using HammadBroker.Model.DTO;
using HammadBroker.Model.Entities;
using HammadBroker.Model.Parameters;
using JetBrains.Annotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using NToastNotify;

namespace HammadBroker.Web.Areas.Admin.Controllers;

[Area(nameof(Admin))]
[Route("[area]/[controller]")]
[Authorize(Policy = Constants.Authorization.AdministrationPolicy)]
public class CitiesController : MvcController
{
	private readonly ICityService _cityService;
	private readonly IDistrictService _districtService;
	private readonly ILookupService _lookupService;
	private readonly IMapper _mapper;
	private readonly IToastNotification _toastNotification;

	/// <inheritdoc />
	public CitiesController([NotNull] ICityService cityService, [NotNull] IDistrictService districtService, [NotNull] ILookupService lookupService, [NotNull] IMapper mapper, [NotNull] IConfiguration configuration, [NotNull] IWebHostEnvironment environment, [NotNull] IToastNotification toastNotification, [NotNull] ILogger<CitiesController> logger)
		: base(configuration, environment, logger)
	{
		_cityService = cityService;
		_districtService = districtService;
		_lookupService = lookupService;
		_mapper = mapper;
		_toastNotification = toastNotification;
	}

	[NotNull]
	[ItemNotNull]
	[HttpGet]
	public async Task<IActionResult> Index([FromQuery(Name = "")] SearchList pagination, CancellationToken token)
	{
		token.ThrowIfCancellationRequested();
		pagination ??= new SearchList();

		if (pagination.OrderBy == null || pagination.OrderBy.Count == 0)
		{
			pagination.OrderBy ??= new List<SortField>(1);
			pagination.OrderBy.Add(new SortField(nameof(City.Name)));
		}

		IPaginated<CityForList> paginated = await _cityService.ListAsync<CityForList>(pagination, token);
		token.ThrowIfCancellationRequested();
		CitiesPaginated result = new CitiesPaginated(paginated.Result, (SearchList)paginated.Pagination);
		token.ThrowIfCancellationRequested();
		return View(result);
	}

	[NotNull]
	[ItemNotNull]
	[AllowAnonymous]
	[Authorize(Policy = Constants.Authorization.MemberPolicy)]
	[HttpGet("[action]")]
	public async Task<IActionResult> List([FromQuery(Name = "")] SearchList pagination, CancellationToken token)
	{
		token.ThrowIfCancellationRequested();
		pagination ??= new SearchList();
		if (!string.IsNullOrEmpty(pagination.Search)) pagination.Search = WebUtility.UrlDecode(pagination.Search);

		if (pagination.OrderBy == null || pagination.OrderBy.Count == 0)
		{
			pagination.OrderBy ??= new List<SortField>(1);
			pagination.OrderBy.Add(new SortField(nameof(City.Name)));
		}

		pagination.PageSize = 0;
		IList<CityForList> result = await _lookupService.ListCitiesAsync(pagination, token);
		token.ThrowIfCancellationRequested();
		return Ok(result);
	}

	[NotNull]
	[HttpGet("[action]")]
	public IActionResult Add(CancellationToken token)
	{
		token.ThrowIfCancellationRequested();
		return View(new CityToUpdate());
	}

	[NotNull]
	[ItemNotNull]
	[HttpPost("[action]")]
	public async Task<IActionResult> Add([NotNull] CityToUpdate cityToAdd, CancellationToken token)
	{
		token.ThrowIfCancellationRequested();
		if (!ModelState.IsValid) return View(cityToAdd);

		City city = await _cityService.AddAsync(_mapper.Map<City>(cityToAdd), token);
		token.ThrowIfCancellationRequested();

		if (city == null)
		{
			_toastNotification.AddSuccessToastMessage("تعذر اضافة المدينة. برجاء المحاولة مرة اخرى بعد مراجعة الحقول المطلوبة");
			return BadRequest();
		}

		_toastNotification.AddSuccessToastMessage($"تم اضافة المدينة '{city.Name}' بنجاح.");
		return RedirectToAction(nameof(Index));
	}

	[NotNull]
	[ItemNotNull]
	[HttpGet("[action]")]
	public async Task<IActionResult> Edit([Required] int id, CancellationToken token)
	{
		token.ThrowIfCancellationRequested();
		if (!ModelState.IsValid) return BadRequest(ModelState);
		CityToUpdate cityToUpdate = await _cityService.GetAsync<CityToUpdate>(id, token);
		token.ThrowIfCancellationRequested();
		if (cityToUpdate == null) return Problem("المدينة غير موجودة.");
		return View(cityToUpdate);
	}

	[NotNull]
	[ItemNotNull]
	[HttpPost("[action]")]
	public async Task<IActionResult> Edit([Required, FromQuery] int id, [NotNull] CityToUpdate cityToUpdate, CancellationToken token)
	{
		token.ThrowIfCancellationRequested();
		if (!ModelState.IsValid) return View(cityToUpdate);
		City city = await _cityService.GetAsync(id, token);
		token.ThrowIfCancellationRequested();

		if (city == null)
		{
			_toastNotification.AddSuccessToastMessage("المدينة غير موجودة.");
			return Problem("المدينة غير موجودة.");
		}

		_mapper.Map(cityToUpdate, city);
		city = await _cityService.UpdateAsync(city, token);
		token.ThrowIfCancellationRequested();

		if (city == null)
		{
			_toastNotification.AddSuccessToastMessage("تعذر تحديث المدينة. برجاء المحاولة مرة اخرى بعد مراجعة الحقول المطلوبة");
			return BadRequest();
		}

		_toastNotification.AddSuccessToastMessage($"تم تحديث المدينة '{city.Name}' بنجاح.");
		return RedirectToAction(nameof(Index));
	}

	[NotNull]
	[ItemNotNull]
	[HttpPost("[action]")]
	public async Task<IActionResult> Delete([Required] int id, CancellationToken token)
	{
		token.ThrowIfCancellationRequested();
		if (!ModelState.IsValid) return BadRequest(ModelState);
		City city = await _cityService.DeleteAsync(id, token);
		token.ThrowIfCancellationRequested();

		if (city == null)
		{
			_toastNotification.AddSuccessToastMessage("المدينة غير موجودة او تعذر حذفها.");
			return Problem("المدينة غير موجودة او تعذر حذفها.");
		}

		_toastNotification.AddSuccessToastMessage($"تم حذف المدينة '{city.Name}' بنجاح.");
		return Ok();
	}

	[NotNull]
	[ItemNotNull]
	[HttpGet("[action]")]
	public async Task<IActionResult> Districts([FromQuery(Name = "")] DistrictList pagination, CancellationToken token)
	{
		token.ThrowIfCancellationRequested();
		pagination ??= new DistrictList();

		if (pagination.OrderBy == null || pagination.OrderBy.Count == 0)
		{
			pagination.OrderBy ??= new List<SortField>(2);
			if (pagination.CityId < 1) pagination.OrderBy.Add(new SortField(nameof(District.CityId)));
			pagination.OrderBy.Add(new SortField(nameof(District.Name)));
		}

		IPaginated<DistrictForList> paginated = await _districtService.ListAsync<DistrictForList>(pagination, token);
		token.ThrowIfCancellationRequested();

		if (pagination.CityId < 1)
		{
			IList<int> citiesIds = paginated.Result
											.Select(e => e.CityId)
											.Distinct()
											.ToList();

			if (citiesIds.Count > 0)
			{
				IDictionary<int, string> cities = await _cityService.Context.Cities
																	.Where(e => citiesIds.Contains(e.Id))
																	.ToDictionaryAsync(k => k.Id, v => v.Name, token);
				token.ThrowIfCancellationRequested();

				foreach (DistrictForList districtForList in paginated.Result)
				{
					if (!cities.TryGetValue(districtForList.CityId, out string cityName)) continue;
					districtForList.CityName = cityName;
				}
			}
		}

		DistrictsPaginated result = new DistrictsPaginated(paginated.Result, (DistrictList)paginated.Pagination);
		return View(result);
	}

	[NotNull]
	[ItemNotNull]
	[AllowAnonymous]
	[Authorize(Policy = Constants.Authorization.MemberPolicy)]
	[HttpGet("[action]")]
	public async Task<IActionResult> ListDistricts([FromQuery(Name = "")] DistrictList pagination, CancellationToken token)
	{
		token.ThrowIfCancellationRequested();
		pagination ??= new DistrictList();
		if (!string.IsNullOrEmpty(pagination.Search)) pagination.Search = WebUtility.UrlDecode(pagination.Search);

		if (pagination.OrderBy == null || pagination.OrderBy.Count == 0)
		{
			pagination.OrderBy ??= new List<SortField>(2);
			if (pagination.CityId < 1) pagination.OrderBy.Add(new SortField(nameof(District.CityId)));
			pagination.OrderBy.Add(new SortField(nameof(District.Name)));
		}

		pagination.PageSize = 0;
		IList<DistrictForList> result = await _lookupService.ListDistrictsAsync(pagination, token);
		token.ThrowIfCancellationRequested();
		return Ok(result);
	}

	[NotNull]
	[HttpGet("[action]")]
	public IActionResult AddDistrict(int cityId, CancellationToken token)
	{
		token.ThrowIfCancellationRequested();
		return View(new DistrictToUpdate
		{
			CityId = cityId
		});
	}

	[NotNull]
	[ItemNotNull]
	[HttpPost("[action]")]
	public async Task<IActionResult> AddDistrict([NotNull] DistrictToUpdate districtToUpdate, CancellationToken token)
	{
		token.ThrowIfCancellationRequested();
		if (!ModelState.IsValid) return View(districtToUpdate);

		District district = await _districtService.AddAsync(_mapper.Map<District>(districtToUpdate), token);
		token.ThrowIfCancellationRequested();

		if (district == null)
		{
			_toastNotification.AddSuccessToastMessage("تعذر اضافة الحي. برجاء المحاولة مرة اخرى بعد مراجعة الحقول المطلوبة");
			return BadRequest();
		}

		_toastNotification.AddSuccessToastMessage($"تم اضافة الحي '{district.Name}' بنجاح.");
		return RedirectToAction(nameof(Districts));
	}

	[NotNull]
	[ItemNotNull]
	[HttpGet("[action]")]
	public async Task<IActionResult> EditDistrict([Required] int id, CancellationToken token)
	{
		token.ThrowIfCancellationRequested();
		if (!ModelState.IsValid) return BadRequest(ModelState);
		DistrictToUpdate districtToUpdate = await _districtService.GetAsync<DistrictToUpdate>(id, token);
		token.ThrowIfCancellationRequested();
		if (districtToUpdate == null) return Problem("الحي غير موجود.");
		return View(districtToUpdate);
	}

	[NotNull]
	[ItemNotNull]
	[HttpPost("[action]")]

HammadBroker.Web/Views/Shared/Components/BuildingViewComponent.cs
using HammadBroker.Model.DTO;
using JetBrains.Annotations;
using Microsoft.AspNetCore.Mvc;

namespace HammadBroker.Web.Views.Shared.Components;

public class BuildingViewComponent : ViewComponent
{
    public BuildingViewComponent()
    {
    }

    [NotNull]
    public IViewComponentResult Invoke([NotNull] BuildingModel model)
    {
        return View(model);
    }
}

HammadBroker.Web/Views/Shared/_Layout.cshtml
@using HammadBroker.Model.Configuration
@using HammadBroker.Model
@using Microsoft.AspNetCore.Http.Extensions
@inject CompanyInfo CompanyInfo
@inject MarketingLinks MarketingLinks
@{
	bool hideMenu = Convert.ToBoolean(ViewBag.HideMenu ?? false);
	string title = string.Join(" - ", ViewData["Title"], CompanyInfo.Name).Trim(' ', '-');
	string image = TempData["Image"]?.ToString();
	string type = TempData["Type"]?.ToString() ?? "website";
}
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
	<link rel="icon" type="image/x-icon" href="@Url.Content("~/favicon.ico")" />
	<link rel="shortcut icon" type="image/x-icon" href="@Url.Content("~/favicon.ico")" />
	<title>@title</title>
	<meta name="description" content="@CompanyInfo.Description" />

	<!--Social media-->
	<meta property="og:title" content="@title" />
	<meta property="og:description" content="@CompanyInfo.Description" />
	<meta property="og:url" content="@Context.Request.GetDisplayUrl()" />
	
	@if (!string.IsNullOrEmpty(image))
	{
		<meta property="og:image" content="@image" />
	}

	<meta property="og:type" content="@type" />
	<meta property="og:locale" content="ar_EG" />

	<link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.rtl.min.css" />
	<link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

	<script type="text/javascript" src="@Url.Content("~/lib/popper.js/umd/popper.min.js")"></script>
	<script type="text/javascript" src="@Url.Content("~/lib/lodash.js/lodash.min.js")"></script>

	<!--VueJs and components-->
	<script type="text/javascript" src="@Url.Content("~/lib/vue/vue.global.min.js")"></script>

	<!--multiselect-->
	<script type="text/javascript" src="@Url.Content("~/lib/vueform/multiselect/dist/multiselect.global.js")">
	</script>
	<link href="~/lib/vueform/multiselect/themes/default.css" asp-append-version="true" rel="stylesheet" />

	<!--primeVue-->
	<link href="~/lib/primevue/resources/themes/bootstrap4-light-blue/theme.css" asp-append-version="true" rel="stylesheet" />
	<link href="~/lib/primevue/resources/primevue.min.css" asp-append-version="true" rel="stylesheet" />
	<link href="~/lib/primeflex/primeflex.min.css" asp-append-version="true" rel="stylesheet" />
	<link href="~/lib/primeicons/primeicons.css" asp-append-version="true" rel="stylesheet" />
	<script type="text/javascript" src="@Url.Content("~/lib/primevue/core/core.min.js")"></script>
	<script type="text/javascript" src="@Url.Content("~/lib/primevue/autocomplete/autocomplete.min.js")"></script>
	<script type="text/javascript" src="@Url.Content("~/lib/primevue/calendar/calendar.min.js")"></script>
	<script type="text/javascript" src="@Url.Content("~/lib/primevue/sidebar/sidebar.min.js")"></script>
	<script type="text/javascript" src="@Url.Content("~/lib/primevue/listbox/listbox.min.js")"></script>
	<script type="text/javascript" src="@Url.Content("~/lib/primevue/galleria/galleria.min.js")"></script>
	<script type="text/javascript" src="@Url.Content("~/lib/primevue/fileupload/fileupload.min.js")"></script>
	<script type="text/javascript" src="@Url.Content("~/lib/primevue/overlaypanel/overlaypanel.min.js")"></script>
	<script type="text/javascript" src="@Url.Content("~/lib/primevue/toast/toast.min.js")"></script>
	<script type="text/javascript" src="@Url.Content("~/lib/primevue/toastservice/toastservice.min.js")"></script>

	@*Last*@
	<link href="@Url.Content("~/css/site.css")" rel="stylesheet" asp-append-version="true" />
	<script type="text/javascript" src="@Url.Content("~/js/site.js")" asp-append-version="true"></script>
	@await RenderSectionAsync("styles", false)
	@await RenderSectionAsync("header", false)
</head>
<body class="d-flex flex-column bg-light overflow-auto">
	<header class="container py-1">
		<nav class="navbar navbar-expand-sm bg-light border-bottom box-shadow mb-4">
			<div class="container-fluid">
				<a class="navbar-brand py-0 m-0" menu-route asp-area="" asp-controller="Home" asp-action="Index">
					<img src="@Url.Content("~/images/logo.jpg")" alt="@CompanyInfo.Name" class="img-fluid" style="max-width: 4rem;" />
					<span class="p-1">@CompanyInfo.Name</span>
				</a>
				@if (!hideMenu)
				{
					<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
							aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div id="navbarSupportedContent" class="navbar-collapse collapse d-sm-inline-flex align-items-center">
						<ul class="navbar-nav flex-grow-1 p-0 my-auto">
							<li class="nav-item">
								<a class="nav-link btn border-0 rounded-0" menu-route asp-area="" asp-page="/About">من نحن</a>
							</li>
							<li class="nav-item dropdown" policy="@Constants.Authorization.AdministrationPolicy">
								<a class="nav-link btn border-0 rounded-0 dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">الاعلانات</a>
								<ul class="dropdown-menu">
									<li><a class="dropdown-item" asp-area="Admin" asp-controller="Buildings" asp-action="Index">عرض</a></li>
									<li><a class="dropdown-item" asp-area="Admin" asp-controller="Buildings" asp-action="Add">اضافة اعلان</a></li>
								</ul>
							</li>
							<li class="nav-item dropdown" policy="@Constants.Authorization.AdministrationPolicy">
								<a class="nav-link btn border-0 rounded-0 dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">المدن</a>
								<ul class="dropdown-menu">
									<li><a class="dropdown-item" asp-area="Admin" asp-controller="Cities" asp-action="Index">عرض</a></li>
									<li><a class="dropdown-item" asp-area="Admin" asp-controller="Cities" asp-action="Add">اضافة مدينة</a></li>
								</ul>
							</li>
							<li class="nav-item dropdown" policy="@Constants.Authorization.AdministrationPolicy">
								<a class="nav-link btn border-0 rounded-0 dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">الأحياء</a>
								<ul class="dropdown-menu">
									<li><a class="dropdown-item" asp-area="Admin" asp-controller="Cities" asp-action="Districts">عرض</a></li>
									<li><a class="dropdown-item" asp-area="Admin" asp-controller="Cities" asp-action="AddDistrict">اضافة حي</a></li>
								</ul>
							</li>
						</ul>
						@if (MarketingLinks.HasLinks)
						{
							<ul class="navbar-nav flex-shrink-1 p-0 my-auto align-self-end marketing-links marketing-links-small">
								@foreach (MarketingLink link in MarketingLinks.Links)
								{
									<li class="nav-item marketing-link @link.CssClass">
										<a href="@link.Url" title="@link.Title" target="_blank"></a>
									</li>
								}
							</ul>
						}
						<partial name="_LoginPartial" />
					</div>
				}
			</div>
		</nav>
	</header>
	<div class="container flex-grow-1 pb-3">
		<main role="main">
			@RenderBody()
		</main>
	</div>

	<footer class="container py-3 mt-2 border-top footer text-muted">
		<div class="d-flex flex-row align-items-center">
			<div class="flex-grow-1">
				<small class="d-inline-block mb-1 text-muted">@CompanyInfo.Name &copy;@DateTime.Today.Year</small>
			</div>
			@if (MarketingLinks.HasLinks)
			{
				<ul class="marketing-links flex-shrink-1">
					@foreach (MarketingLink link in MarketingLinks.Links)
					{
						<li class="marketing-link @link.CssClass">
							<a href="@link.Url" title="@link.Title" target="_blank"></a>
						</li>
					}
				</ul>
			}
		</div>
	</footer>

	<script src="~/lib/jquery/jquery.min.js"></script>
	<script src="~/lib/bootstrap/js/bootstrap.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	
	@await RenderSectionAsync("Scripts", false)
	@Html.PageScripts()
	
	@await Component.InvokeAsync("NToastNotify");
</body>
</html>

HammadBroker.Web/Views/Shared/_PaginationPartial.cshtml
@using System.Text.RegularExpressions
@model essentialMix.Patterns.Pagination.IPagination

@{
	bool showPages = Model.PageSize > 0 && Model.Count > Model.PageSize;
	int pages = showPages
					? (int)Math.Ceiling((double)Model.Count / Model.PageSize)
					: 1;
	string routUrl = Url.RouteUrl(ViewContext.RouteData.Values);
	string queryString = ViewContext.HttpContext.Request.QueryString.Value == null
							? string.Empty
							: Regex.Replace(ViewContext.HttpContext.Request.QueryString.Value, "[?&]page=\\d+", string.Empty);
	char suffix = queryString.IndexOf('?') > -1
					? '&'
					: '?';
	string currentUrl = $"{routUrl}{queryString}";
}

@if (pages > 1)
{
	<nav class="d-flex justify-content-center">
		<ul class="pagination">
			@if (Model.Page == 1)
			{
				<li class="page-item disabled">
					<a class="page-link" aria-label="First">
						<span aria-hidden="true">&laquo;</span>
					</a>
				</li>
				<li class="page-item disabled">
					<a class="page-link" aria-label="Previous">
						<span aria-hidden="true">&lsaquo;</span>
					</a>
				</li>
				<li class="page-item active">
					<a class="page-link">1</a>
				</li>
			}
			else
			{
				<li class="page-item">
					<a class="page-link" href="@($"{currentUrl}{suffix}page=1")" aria-label="First">
						<span aria-hidden="true">&laquo;</span>
					</a>
				</li>
				<li class="page-item">
					<a class="page-link" href="@($"{currentUrl}{suffix}page={Model.Page - 1}")" aria-label="Previous">
						<span aria-hidden="true">&lsaquo;</span>
					</a>
				</li>
				<li class="page-item">
					<a class="page-link" href="@($"{currentUrl}{suffix}page=1")">1</a>
				</li>
			}
			@if (pages < 7)
			{
				for (int i = 2; i < pages; i++)
				{
					<li class="page-item @(Model.Page == i ? "active" : null)">
						<a class="page-link" href="@(Model.Page == i ? null : $"{currentUrl}{suffix}page={i}")">@i</a>
					</li>
				}
			}
			else
			{
				int start = (Model.Page - 1).Within(3, pages - 4);
				int end = (Model.Page + 1).Within(start + 3, pages - 1);

				if (start > 3)
				{
					<li class="page-item">
						<a class="page-link" href="@($"{currentUrl}{suffix}page={start - 1}")">&mldr;</a>
					</li>
				}
				else
				{
					<li class="page-item @(Model.Page == 2 ? "active" : null)">
						<a class="page-link" href="@(Model.Page == 2 ? null : $"{currentUrl}{suffix}page=2")">2</a>
					</li>
				}
				for (int i = start; i < end; i++)
				{
					<li class="page-item @(Model.Page == i ? "active" : null)">
						<a class="page-link" href="@(Model.Page == i ? null : $"{currentUrl}{suffix}page={i}")">@i</a>
					</li>
				}
				if (end < pages - 1)
				{
					<li class="page-item">
						<a class="page-link" href="@($"{currentUrl}{suffix}page={end + 1}")">&mldr;</a>
					</li>
				}
				else
				{
					<li class="page-item @(Model.Page == end ? "active" : null)">
						<a class="page-link" href="@(Model.Page == end ? null : $"{currentUrl}{suffix}page={end}")">@end</a>
					</li>
				}
			}
			@if (Model.Page < pages)
			{
				<li class="page-item">
					<a class="page-link" href="@($"{currentUrl}{suffix}page={pages}")">@pages</a>
				</li>
				<li class="page-item">
					<a class="page-link" href="@($"{currentUrl}{suffix}page={Model.Page + 1}")" aria-label="Next">
						<span aria-hidden="true">&rsaquo;</span>
					</a>
				</li>
				<li class="page-item">
					<a class="page-link" href="@($"{currentUrl}{suffix}page={pages}")" aria-label="Last">
						<span aria-hidden="true">&raquo;</span>
					</a>
				</li>
			}
			else
			{
				<li class="page-item active">
					<a class="page-link">@pages</a>
				</li>
				<li class="page-item disabled">
					<a class="page-link" aria-label="Next">
						<span aria-hidden="true">&rsaquo;</span>
					</a>
				</li>
				<li class="page-item disabled">
					<a class="page-link" aria-label="Last">
						<span aria-hidden="true">&raquo;</span>
					</a>
				</li>
			}
		</ul>
	</nav>
}